FROM golang:1.23.4-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /go/bin/shippingservice .

FROM scratch

WORKDIR /src
COPY --from=builder /go/bin/shippingservice /src/shippingservice

USER 1000:1000
ENTRYPOINT ["/src/shippingservice"]
