{{- if .Values.shippingservice.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shippingservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.shippingservice.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.shippingservice.name }}
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
{{- end }} 