FROM node:20.18.1 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

FROM gcr.io/distroless/nodejs20-debian12:nonroot

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY . .


USER 1000:1000
CMD ["server.js"]
