{{- range .Values.networkPolicies }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}
