{{- if .Values.checkoutservice.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.checkoutservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.checkoutservice.name }}
spec:
  replicas: {{ .Values.checkoutservice.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.checkoutservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.checkoutservice.name }}
    spec:
      serviceAccountName: {{ .Values.checkoutservice.name }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
        {{- with .Values.checkoutservice.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecretName }}
      containers:
        - name: {{ .Values.checkoutservice.name }}
          image: "{{ .Values.checkoutservice.image.repository }}:{{ .Values.checkoutservice.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:8080"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
          resources:
            {{- toYaml .Values.checkoutservice.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
            {{- with .Values.checkoutservice.containerSecurityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            grpc:
              port: 5050
          livenessProbe:
            grpc:
              port: 5050
{{- end }} 