{{- if .Values.cartservice.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.cartservice.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.cartservice.name }}
  ports:
    - port: 7070
      targetPort: 7070
      protocol: TCP
      name: http
{{- end }}