{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Values.frontend.name }}
      port:
        number: 80
{{- end }}
